name: generate data
on: workflow_dispatch
jobs:
  produce_and_push_data:
    name: produce and push data
    runs-on: ubuntu-latest
    env:
      GITLAB_SOURCE_TOKEN: ${{ secrets.GITLAB_DATA_DOWNLOAD_TOKEN }}
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      GITHUB_ACCESS_TOKEN_NAME: ${{ secrets.GITHUB_ACCESS_TOKEN_NAME }}
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      GH_USERMAIL: ${{ secrets.GH_USERMAIL }}

    steps:
      - uses: actions/checkout@v4
      - name: produce data
        run: |
          pip install -r pyscripts/requirements.txt
          ./shellscripts/dl_and_prepare_gl_data.sh
          ./shellscripts/extract_infos.sh
      - name: push data to private repo
        run: |
          git config --global user.email "${GH_USERMAIL}"
          git config --global user.name "${GH_USERNAME}"
          git config --global credential.helper cache
          mkdir cloned_repo
          git clone https://${GITHUB_ACCESS_TOKEN_NAME}:${GITHUB_ACCESS_TOKEN}@github.com/Flugblatter/flugblaetter_data_output.git cloned_repo
          cp -r out/* cloned_repo/
          cd cloned_repo
          git add .
          git commit -m "$(date) new data"
          git push