name: generate data
on: [workflow_dispatch, push]
jobs:
  produce_and_push_data:
    name: produce and push data
    runs-on: ubuntu-latest
    env:
      GITLAB_SOURCE_TOKEN: ${{ secrets.GITLAB_DATA_DOWNLOAD_TOKEN }}
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHB_ACCESS_TOKEN }}
      GITHUB_ACCESS_TOKEN_NAME: ${{ secrets.GITHB_ACCESS_TOKEN_NAME }}
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      GH_USERMAIL: ${{ secrets.GH_USERMAIL }}

    steps:
      - uses: actions/checkout@v4
      - name: produce data
        run: |
          pip install -r pyscripts/requirements.txt
          ./shellscripts/dl_and_prepare_gl_data.sh
          pip install -r ./pyscripts/requirements.txt
          python ./pyscripts/extract_data.py
      - name: clone target repo
        run: |
          git config --global user.email "${GH_USERMAIL}"
          git config --global user.name "${GH_USERNAME}"
          git config --global credential.helper cache
          mkdir cloned_repo
          git clone https://${GITHUB_ACCESS_TOKEN_NAME}:${GITHUB_ACCESS_TOKEN}@github.com/Flugblatter/flugblaetter_data_ouput.git cloned_repo
          ls -la cloned_repo
      - name: push data to target repo
        run: |
          cp -r out/* cloned_repo/
          cd cloned_repo
          git add .
          git commit -m "$(date) new data"
          status=`git status`
          echo $status
          if [[ $status == *"git add"* ]]; then
            echo "changes detected"
            git push
          else
            echo "nothing to push"
          fi



